### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [FedorovaDarya/Ciphxor#1]
1. При кодировании Вы делаете xor между символом файла и байтом ключа. Но символ не всегда влазит в один байт, так что у Вас будут проблемы при кодировании файлов, например, с русскими символами.
1. Предполагалось, что байты будут выводится файл без перевода в строковое шестнадцатеричное представление и закодированный файл будет содержать то же число байт, что и исходный.
1. Из предыдущего замечания следует, что процессы кодирования и декодирования ничем не отличаются, так что делать для ни разные функции не нужно.
1. По заданию, производится либо кодирование, либо декодирование, но не оба сразу.

**Comment by DariyaFedorova** [comment]
Спасибо. Замечания учтены.
